Klipper\Component\DoctrineExtensionsExtra\Filterable\FilterConfig:
    exclusion_policy: all
    properties:
        filters:
            groups: [Default]
        groups:
            groups: [Default]
