Klipper\Component\DoctrineExtensionsExtra\Representation\Pagination:
    exclusion_policy: all
    properties:
        page:
            groups: [Default, Public]
        limit:
            groups: [Default, Public]
        pages:
            groups: [Default, Public]
        total:
            groups: [Default, Public]
        results:
            groups: [Default, Public]
